FROM nginx

#####################################################################
# SETTING UP APPLICATION DIRECTORY AND ENVIRONMENT VARIABLES
#####################################################################
RUN mkdir -p /usr/share/nginx/html
COPY dist /usr/share/nginx/html


EXPOSE 80